server:
  port: 8003
spring:
  application:
    name: api-auth
  redis:
    hostserver: localhost:6379 #该节点配置redis单机，配置后下面哨兵模式失效
    database: 4 # Redis数据库索引（默认为0）
    timeout: 10000 # 连接超时时间（毫秒）
    password:  # Redis服务器连接密码（默认为空）
    perKey: general_redis #redis前缀
    sentinel:
      master: mymaster
      nodes:
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

